#version 460
#extension GL_GOOGLE_include_directive : require
// on utilise des trucs de 16x16 pixels
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


struct	GPUMaterial
{
	vec3	color;
	float	roughness;
	vec3	emission;
	float	metallic;
	float	ior;
	int		type;
	int		albedo_tex_idx;
	int		normal_tex_idx;
	int		r_tex_idx;
	int		m_tex_idx;
	int		e_tex_idx;
	int		is_opaq;
	int		is_spec;
	int		pad0;
	int		pad1;
	int		pad2; 
};

struct	GPUTriangle
{
	vec3	v0;
	int		mat_idx;
	vec3	v1;
	float	uv0_x;
	vec3	v2;
	float	uv0_y;
	float	uv1_x;
	float	uv1_y;
	float	uv2_x;
	float	uv2_y;
};

struct	GPUSphere
{
	mat4	inverse_transform;
	vec3	center;
	float	radius;
	int		mat_idx;
	float	pad[3];
};

struct	GPUQuad
{
	mat4	inverse_transform;
	vec3	center;
	int		mat_idx;
	vec3	normal;
	float	w;
	float	h;
	float	pad[3];
};

struct	GPUPlane
{
	mat4	inverse_transform;
	vec3	point;
	int		mat_idx;
	vec3	normal;
	int		pad0;
};

struct GPUBVHNode
{
	vec3	aabb_min;
	int		left_child_or_prim_offset;
	vec3	aabb_max;
	int		right_child;
	int		prim_count;
	int		axis;
	int		pad[2];
};

struct	GPULight
{
	int	prim_type;
	int	prim_idx;
	int	pad[2];
};

//binding buffer
layout(std430, binding = 0) readonly buffer MatBuf
{
	GPUMaterial materials[];
};
layout(std430, binding = 1) readonly buffer TriBuf
{
	GPUTriangle triangles[];
};
layout(std430, row_major, binding = 2) readonly buffer SphBuf
{
	GPUSphere spheres[];
};
layout(std430, row_major, binding = 3) readonly buffer QdBuf 
{
	GPUQuad quads[];
};
layout(std430, row_major, binding = 4) readonly buffer PlBuf 
{
	GPUPlane planes[];
};
layout(std430, binding = 5) readonly buffer BVHTriBuf
{
	GPUBVHNode bvh_triangles[];
};
layout(std430, binding = 6) readonly buffer BVHSphBuf
{
	GPUBVHNode bvh_spheres[];
};
layout(std430, binding = 7) readonly buffer BVHQdBuf 
{
	GPUBVHNode bvh_quads[];
};

// Le buffer de sortie (Binding 8)
layout(std430, binding = 8) buffer OutBuf
{
	uint pixels[];
};

layout(std430, binding = 9) readonly buffer LightBuf
{
	GPULight lights[];
};

layout(std430, binding = 10) buffer AccumBuf
{
	vec4	accum_buffer[];
};


layout(push_constant) uniform PushConstants
{
	vec3		cam_origin;
	float		pad0;
	vec3		cam_forward;
	float		pad1;
	vec3		cam_right;
	float		pad2;
	vec3		cam_up;
	float		fov;
	int			frame_count;
	int			max_depth;
	uint		seed;
	float		time;
	int			w_h;
	int			w_w;
	uint		light_count;
	int			shadow_ray;
	int			ru_enabled;
	int			pad[3];
} pc;

struct	Ray
{
	vec3	o;
	vec3	dir;
};

struct	HitRecord
{
	vec3	point;
	vec3	normal;
	float	t;
	float	u;
	float	v;
	bool	front_face;
	int		mat_idx;
	float	ni_from;
};

#define MAT_LAMBERTIAN 0
#define MAT_METAL 1
#define MAT_DIELECTRIC 2
#define MAT_PBR 3
#define MAT_LIGHT 4
#define M_PI 3.14159265358979323846

#include "random_utils.glsl"
#include "intersection.glsl"
#include "materials.glsl"
#include "hit_bvhs.glsl"
#include "pdf_values.glsl"
#include "shadow.glsl"
#include "traceray.glsl"


void	main()
{
	ivec2	pixel_coords = ivec2(gl_GlobalInvocationID.xy);
	ivec2	resolution = ivec2(pc.w_w, pc.w_h);

	if (pixel_coords.x >= resolution.x || pixel_coords.y >= resolution.y)
		return ;
	int		pixel_index = pixel_coords.y * resolution.x + pixel_coords.x;
	vec2	uv = vec2(pixel_coords) / vec2(resolution);
	float	ndc_x = (2.0 * uv.x) - 1.0;
	float	ndc_y = 1.0 - (2.0 * uv.y); 
	float	aspect = float(resolution.x) / float(resolution.y);
	float	half_h = tan(radians(pc.fov) * 0.5);
	float	half_w = half_h * aspect;
	vec3	ray_dir = pc.cam_forward + pc.cam_right * (ndc_x * half_w) 
					+ pc.cam_up * (ndc_y * half_h);
	ray_dir = normalize(ray_dir);
	vec3	ray_origin = pc.cam_origin;
	Ray		ray = Ray(ray_origin, ray_dir);
	uint pixel_seed = pc.seed + uint(pixel_index);
	pixel_seed = pcg_hash(pixel_seed);
	vec3	color = traceRay(ray, pixel_seed);
	vec3	accumulated_color;
	
	if (pc.frame_count == 1)
	{
		accumulated_color = color;
		accum_buffer[pixel_index] = vec4(accumulated_color, 1.0);
	}
	else
	{
		accumulated_color = accum_buffer[pixel_index].rgb + color;
		accum_buffer[pixel_index] = vec4(accumulated_color, 1.0);
	}
	vec3 base = accumulated_color / float(pc.frame_count);
	vec3 fc = max(vec3(0.0), base);
	fc = pow(fc / (fc + vec3(1.0)), vec3(1.0 / 2.2));
	uvec3 irgb = uvec3(min(vec3(1.0), fc) * 255.999);
	pixels[pixel_index] = (irgb.r << 24) | (irgb.g << 16) | (irgb.b << 8) | 0xFFu;
}
