#version 460
#extension GL_GOOGLE_include_directive : require
// on utilise des truc de 16x16 pixel
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;


struct	GPUMaterial
{
	vec3	color;
	float	roughness;
	vec3	emission;
	float	metallic;
	float	ior;
	int		type;
	int		albedo_tex_idx;
	int		normal_tex_idx;
	int		r_tex_idx;
	int		m_tex_idx;
	int		e_tex_idx;
	int		pad0;
};

struct	GPUTriangle
{
	vec3	v0;
	int		mat_idx;
	vec3	v1;
	float	uv0_x;
	vec3	v2;
	float	uv0_y;
	float	uv1_x;
	float	uv1_y;
	float	uv2_x;
	float	uv2_y;
};

struct	GPUSphere
{
	mat4	inverse_transform;
	vec3	center;
	float	radius;
	int		mat_idx;
	float	pad[3];
};

struct	GPUQuad
{
	mat4	inverse_transform;
	vec3	center;
	int		mat_idx;
	vec3	normal;
	float	w;
	float	h;
	float	pad[3];
};

struct	GPUPlane
{
	mat4	transform;
	mat4	inverse_transform;
	vec3	point;
	int		mat_idx;
	vec3	normal;
	int		pad0;
};

struct GPUBVHNode
{
	vec3	aabb_min;
	int		left_child_or_prim_offset;
	vec3	aabb_max;
	int		right_child;
	int		prim_count;
	int		axis;
	int		pad[2];
};

//binding buffer
layout(std430, binding = 0) readonly buffer MatBuf
{
	GPUMaterial materials[];
};
layout(std430, binding = 1) readonly buffer TriBuf
{
	GPUTriangle triangles[];
};
layout(std430, binding = 2) readonly buffer SphBuf
{
	GPUSphere spheres[];
};
layout(std430, binding = 3) readonly buffer QdBuf 
{
	GPUQuad quads[];
};
layout(std430, binding = 4) readonly buffer PlBuf 
{
	GPUPlane planes[];
};
layout(std430, binding = 5) readonly buffer BVHTriBuf
{
	GPUBVHNode bvh_triangles[];
};
layout(std430, binding = 6) readonly buffer BVHSphBuf
{
	GPUBVHNode bvh_spheres[];
};
layout(std430, binding = 7) readonly buffer BVHQdBuf 
{
	GPUBVHNode bvh_quads[];
};

// Le buffer de sortie (Binding 8)
layout(std430, binding = 8) writeonly buffer OutBuf
{
	uint pixels[];
};
layout(push_constant) uniform PushConstants
{
	vec3		cam_origin;
	float		pad0;
	vec3		cam_forward;
	float		pad1;
	vec3		cam_right;
	float		pad2;
	vec3		cam_up;
	float		fov;
	int			frame_count;
	int			max_depth;
	uint		seed;
	float		time;
	int			w_h;
	int			w_w;
	vec2		pad3;
} pc;

#include "intersection.glsl"

uint	packColor(vec3 color)
{
	uvec3 c = uvec3(clamp(color, 0.0, 1.0) * 255.0);
	return (c.r << 24) | (c.g << 16) | (c.b << 8) | 255u;
}


void	main()
{
	ivec2	pixel_coords = ivec2(gl_GlobalInvocationID.xy);
	ivec2	resolution = ivec2(pc.w_w, pc.w_h);

	if (pixel_coords.x >= resolution.x || pixel_coords.y >= resolution.y)
		return ;
	int		pixel_index = pixel_coords.y * resolution.x + pixel_coords.x;
	vec2	uv = vec2(pixel_coords) / vec2(resolution);
	float	ndc_x = (2.0 * uv.x) - 1.0;
	float	ndc_y = 1.0 - (2.0 * uv.y); 
	float	aspect = float(resolution.x) / float(resolution.y);
	float	half_h = tan(radians(pc.fov) * 0.5);
	float	half_w = half_h * aspect;
	vec3	ray_dir = pc.cam_forward + pc.cam_right * (ndc_x * half_w) 
					+ pc.cam_up * (ndc_y * half_h);
	ray_dir = normalize(ray_dir);
	vec3	ray_origin = pc.cam_origin;
	vec3	color = abs(ray_dir);
    pixels[pixel_index] = packColor(color);
}
